FROM docker.io/library/ubuntu:18.04

LABEL org.opencontainers.image.source=https://github.com/computator/deluge-container
LABEL run='podman run --name $NAME -it -v ${NAME}-download:/download -v /tmp/.X11-unix:/tmp/.X11-unix:ro -e DISPLAY $OPT1 $IMAGE'

RUN set -eux; \
	apt-get update; \
	apt-get -y install --no-install-recommends ca-certificates curl; \
	curl -sS 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8eed8fb4a8e6da6dfdf0192bc5e6a5ed249ad24c' \
		| tee /usr/share/keyrings/deluge-archive-keyring.asc; \
	. /etc/lsb-release; \
	echo "deb [signed-by=/usr/share/keyrings/deluge-archive-keyring.asc] https://ppa.launchpadcontent.net/deluge-team/ppa/ubuntu ${DISTRIB_CODENAME} main" \
		> /etc/apt/sources.list.d/deluge.list; \
	{ \
		echo 'Package: *'; \
		echo 'Pin: release o=LP-PPA-deluge-team'; \
		echo 'Pin-Priority: 1000'; \
	} | tee /etc/apt/preferences.d/deluge.pref; \
	apt-get update; \
	apt-get -y install --no-install-recommends deluge-gtk deluge-console; \
	rm -rf /var/lib/apt/lists/*
COPY entrypoint.gui.sh /usr/local/bin/entrypoint.sh

RUN set -eux; \
	mkdir -p /config; \
	{ \
		echo '{'; \
		echo '	"file": 1,'; \
		echo '	"format": 1'; \
		echo '}{'; \
		echo '	"classic_mode": false,'; \
		echo '	"choose_directory_dialog_path": "/download"'; \
		echo '}'; \
	} | tee /config/gtkui.conf

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["deluge-gtk"]

WORKDIR /download
VOLUME /config
VOLUME /download
